security:
  oauth2:
    academy:
      client-id: academy-service
      client-secret: academy-service
    club:
      client-id: club-service
      client-secret: club-service
    player:
      client-id: player-service
      client-secret: player-service