package net.skideo.model.enums;

public enum Region {

    CIS,WESTERN_EUROPE,NORTHERN_EUROPE,SOUTHERN_EUROPE,EASTERN_EUROPE,
    EAST_ASIA,CENTRAL_ASIA,NEAR_EAST,LATIN_AMERICA,CENTRAL_AMERICA,
    NORTH_AMERICA,NORTH_AFRICA,CENTRAL_AFRICA,SOUTH_AFRICA

}
