zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 40000
    socket-timeout-millis: 40000
  routes:
    academy:
      path: /academy/**
      url: http://localhost:9050
    oauth:
      path: /oauth/**
      url: http://localhost:9080
    club:
      path: /club/**
      url: http://localhost:7000
    player:
      path: /player/**
      url: http://localhost:9000
    scout:
      path: /scout/**
      url: http://localhost:8050
    notification:
      path: /notification/**
      url: http://localhost:9030